### ISSUE TITLE
Missing License Specification

### ISSUE THREAD

**Issue by JacobCarrell** [simonlourson/blueprintnotincluded#6]
Currently No license is specified in Github's Project License option, nor is one listed in the project source (typically license.txt or license.md).

The problem with this is without it there's no way to determine if you can use BPNI in your projects. No license is not a presumption of Public Domain, and even if it was I don't expect that's what the author intended.

Please Spend 5min to add FOSS/OSS license details. 

https://choosealicense.com/ goes through a step by step basis of picking a license to make it easier for use non lawyers to figure out what we want.

**Comment by simonlourson** [comment]
Done
